/**
 * Fails the build when a composition's assets are not in the repo.
 *
 * This exists because of a specific way this project can break. The music beds
 * are generated by `scripts/make-bed*.js` and land in `public/`, which means it
 * is entirely possible — and did happen — to render a piece locally, be happy
 * with it, and commit everything except the bed it depends on. Nothing fails:
 * `tsc` passes, the CLI renders, Studio plays. The first sign of trouble is a
 * deployed page playing a film in silence.
 *
 * `staticFile()` is a runtime lookup, so nothing upstream of the browser can
 * catch this. A build-time check can, and it costs milliseconds.
 *
 * Captures under `public/screens/` are deliberately not checked: they are
 * gitignored on purpose (large, stale quickly, may hold real user data) and the
 * gallery already says so on the pieces that use them.
 */

const fs = require("node:fs");
const path = require("node:path");

const PUBLIC_DIR = path.join(__dirname, "..", "public");

/** file in public/ -> how to get it back. */
const REQUIRED = {
  "bed.mp3": "already committed; restore with `git checkout public/bed.mp3`",
  "bed16.mp3": "npm run bed16",
  "bed30.mp3": "npm run bed30",
  "bed36.mp3": "npm run bed36",
  "bed38.mp3": "npm run bed38",
  "bed90.mp3": "npm run bed90",
  "bed-update.mp3": "npm run bed-update",
  "skng-logo.png": "from the product's public/ — not generated",
  "skng-lockup-dark.png": "from the product's public/modes/ — not generated",
  "skng-lockup-light.png": "from the product's public/modes/ — not generated",
};

const missing = Object.keys(REQUIRED).filter(
  (file) => !fs.existsSync(path.join(PUBLIC_DIR, file)),
);

if (missing.length === 0) {
  console.log(
    `check-assets: ${Object.keys(REQUIRED).length} required assets present.`,
  );
  process.exit(0);
}

console.error("");
console.error(
  `check-assets: ${missing.length} required asset${missing.length === 1 ? "" : "s"} missing from public/.`,
);
console.error("");
for (const file of missing) {
  console.error(`  ${file.padEnd(24)} ${REQUIRED[file]}`);
}
console.error("");
console.error(
  "These are referenced by staticFile(), so a build would succeed and the",
);
console.error("deployed piece would fail silently. Fix them and build again.");
console.error("");
process.exit(1);
